### ISSUE TITLE
Sample error

### ISSUE THREAD

**Issue by onytoo** [kodhework/kodnet#1]
OLE IDispatch exception code 0 from mscorlib: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type...

**Comment by voxsoftware** [comment]
Please share in what portion of code is throwing the error. Also share the windows version and VFP version used

**Comment by JulioNobre** [comment]
First of all, would like to thank to **VoxSoftware** on sharing such an important peace of code.

Regarding to **onytoo**'s referenced bug, I have found that two of the first three samples were incorrect. I had revised the English version of **README.MD** file (see attached zip file). 

In case one interested, I am available to help on improving Spanish version of README.esLA.md file .

Again, thanks a lot 👍 

[README.zip](https://github.com/voxsoftware/kodnet/files/2856583/README.zip)

**Comment by voxsoftware** [comment]
@JulioNobre  can you make a fork, and a pull request for see exactly what you changed please? Thanks

**Comment by JulioNobre** [comment]
Please check JulioNobre-patch-2 pull request and confirm me whether it fits. Forget about JulioNobre-patch-1.

**Comment by voxsoftware** [comment]
OK, merged @JulioNobre

**Comment by voxsoftware** [comment]
@onytoo  due to inativity i will close the issue. Open a new issue with detailed info about error and your environment
