### ISSUE TITLE
OLE IDispatch exception code 0 from mscorlib: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type...

### ISSUE THREAD

**Issue by onytoo** [kodhework/kodnet#3]
VFP 9 SP2 with latest hotfix 7423
Windows 10 Home Single Language 64-bit
Installed .Net Framework 4.5.1 and 4.5.2

Run sample: webcam

**Comment by voxsoftware** [comment]
Please share the portion of code when is thrown the exception

**Comment by voxsoftware** [comment]
@onytoo  how are you running the example? you should run the webcam.prg before execute the form? Another question, are you using the Aforge libraries included in the project or are using a newer version? If you are using a newer version, maybe means that Aforge changed the delegate signature

**Comment by onytoo** [comment]
> @onytoo how are you running the example? you should run the webcam.prg before execute the form? Another question, are you using the Aforge libraries included in the project or are using a newer version? If you are using a newer version, maybe means that Aforge changed the delegate signature

yes i have running kodnet.prg and webcam.prg at first before run webcam form

**Comment by onytoo** [comment]
> @onytoo how are you running the example? you should run the webcam.prg before execute the form? Another question, are you using the Aforge libraries included in the project or are using a newer version? If you are using a newer version, maybe means that Aforge changed the delegate signature

I'm just run the samples you included nothing else, so I think i'm using that in LIB folder

**Comment by onytoo** [comment]
I tried all samples you included, error happen only in webcam sample

**Comment by voxsoftware** [comment]
ok @onytoo  i am not able to reproduce from my side (i have similar environment). Contact me to contacto@kodhe.com and i will try check your problem with more deep

**Comment by onytoo** [comment]
I think this problems caused by aforge library, so lets we skip this problem and move on, since it just an example, nothing matter. thanks for your effort.

**Comment by voxsoftware** [comment]
I talked with other people, and seems that they can start the webcam example without any problem. I am agree with you that problem should be related to aforge delegate definition, but i am not sure why you have this error and others no. Let me know if you have any other problem or question. I will be here with this project.
