### ISSUE TITLE
Outlook E-Mail

### ISSUE THREAD

**Issue by Amarrete** [kodhework/kodnet#4]
I was wondering if it was possible to automate Outlook from FoxPro using kodnet (the endgame is to see if we can overcome the 32 bit limitation, as now we need to keep installing office 32 bits to be able to use automation from FoxPro) so I tried this two methods, they both fail in the last line, you can see that I did not get far, as the object returned seems to be an empty shell without properties or methods (but no error), anyways, this is the code I tried:

```
local OutlookApplicationClass, OutlookApplicationObject

_screen.kodnet.loadAssemblyFile("C:\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Outlook\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Outlook.dll")
m.OutlookApplicationClass		= _screen.kodnet.getStaticWrapper("Microsoft.Office.Interop.Outlook.Application")
m.OutlookApplicationObject		= m.OutlookApplicationClass.construct() && << OutlookApplicationClass is an object without visible methods or properties


** This looks better as we do not need to put all the gibberish path as above
_screen.dotnet4.loadAssemblyPartialName('Outlook.Application')
_screen.dotnet4.getStaticWrapper("Microsoft.Office.Interop.Outlook.Application")
m.OutlookApplicationObject		= m.OutlookApplicationClass.construct() && Empty object none the less

```

I am using VFP 9 SP2, Outlook 2013 32 bits and Windows 10 64

TIA,
Hugo

**Comment by RickStrahl** [comment]
I wouldn't think so - you still have to load the 32 bit .NET Framework in-process into a 32 bit process and the office automation objects then too have to use 32 bit.

**Comment by voxsoftware** [comment]
@Amarrete all objects returned by kodnet are COM. This means, that VFP cannot show methods in editor or command windows. How you know that have no methods or properties?

**Comment by voxsoftware** [comment]
@Amarrete Just now i tested, and my observations

1. You don't need outlook 32bit version for make interop from VisualFoxPro, you can make interop with Outlook 64 bit. (I tested)
2. In .NET you need use Microsoft.Office.Interop.Outlook.Application but from kodnet you need use **Microsoft.Office.Interop.Outlook.ApplicationClass**, that is the real underlying class, Microsoft.Office.Interop.Outlook.Application is only the interface


```foxpro 

local OutlookApplicationClass, OutlookApplicationObject

* for this example you need install Microsoft.Outlook, this example was tested with Outlook 2013 x64
_screen.kodnet.loadAssemblyFile("C:\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Outlook\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Outlook.dll")

m.OutlookApplicationClass		= _screen.kodnet.getStaticWrapper("Microsoft.Office.Interop.Outlook.ApplicationClass")
m.OutlookApplicationObject		= m.OutlookApplicationClass.construct() 
MESSAGEBOX(m.OutlookApplicationObject.version)
```


I will mark as solved. Thanks for your report. See the example running in my side: 
![Screenshot](https://storage-ns01.d0stream.com/.drive/Screenshots/outlook-interop.png)

**Comment by voxsoftware** [comment]
@RickStrahl  like you see in my previous comment, **kodnet** can interop with 64bit Outlook and framework without problem
