### ISSUE TITLE
System.IO.DLL  I cant not get classes or Enums for this Assemble

### ISSUE THREAD

**Issue by JALIMA** [kodhework/kodnet#5]
I Think we needs more examples,  maybe we can share each others as well we  creates somes solutions.

I have no way to get Classes from System.IO.DLL like FILE OR FILESTREAM either Enum like System.IO.FileMode Enum

Apart, i run this code and toesnt work for me
directoriesClass = _screen.dotnet4.getStaticWrapper("System.IO.Directory") y receive the
errr can get a wrapper for the type System.IO.Directory, i will like to expect  the error messages more explainded.

I will to Thank you  to make this Utility possible.

**Comment by voxsoftware** [comment]
I cannot reproduce the error you mentioned. I can get wrapper without problem. I execute kodnet.prg and later execute on command window: 

```_screen.kodnet.getStaticWrapper("System.IO.Directory")```

no error.

**Comment by voxsoftware** [comment]
How I don't have more info to process the bug, i will close
