### ISSUE TITLE
pass vfp numeric array to modules 

### ISSUE THREAD

**Issue by mbanco** [kodhework/kodnet#6]
Hi,
I have problems with the next code:

do fullpath("kodnet.prg")

TEXT TO m.code noshow

using System;
using System.Collections.Generic;
using System.IO;

public class program{

	public static void main(){
	

	}
}

namespace Compiled
{

	public class outliers{

        public double index { get; set; }

        public double replacements { get; set; }

    }	
	
	
	public class datos{

        public double consumo { get; set; }

    }	
	
	
	public class Test
	{	
		
		
		public List<outliers> Routliers(ref double[,] datos) {

			List<outliers> resultado = new List<outliers>();

		        for (int i = 0; i <= 19 - 1; i++)
		        {
			
		           resultado.Add(new outliers { index = datos[i,1], replacements = datos[i,1] });

			}	
		
		
			return resultado;
						
		}
		
		
		
		
	
		public static int ExecuteFunc(Func<string,int> func)
		{
			return func("Method executed from .NET");
		}
		
		public static int ExecuteFunc(Func<string,int> func, string message)
		{
			return func(message);
		}
		
		public static int ExecuteFunc(Func<string,int,string,int> func, string message, int option, string title)
		{
			return func(message,option,title);
		}
	}
}

ENDTEXT 

LOCAL engine

* COMPILE C# CODE
Local asem, test

engine = _screen.kodnet.getStaticWrapper("jxshell.csharplanguage").construct()
m.engine.Runscript(m.code)
asem = m.engine.getCompiledAssembly()
_Screen.kodnet.loadAssembly(m.asem)

* now you can use the type compiled 
test = _screen.kodnet.getStaticWrapper("Compiled.Test").construct()

LOCAL ARRAY m_datos(19, 1) as Double  

m_datos(1,1) = 378
m_datos(2,1) = 327
m_datos(3,1) = 311
m_datos(4,1) = 329
m_datos(5,1) = 801
m_datos(6,1) = 1238
m_datos(7,1) = 449
m_datos(8,1) = 408
m_datos(9,1) = 452
m_datos(10,1) = 442
m_datos(11,1) = 947
m_datos(12,1) = 1617
m_datos(13,1) = 451
m_datos(14,1) = 495
m_datos(15,1) = 489
m_datos(16,1) = 391
m_datos(17,1) = 1182
m_datos(18,1) = 1132
m_datos(19,1) = 380

resultado = test.Routliers(m_datos)

FOR n = 0 TO resultado.COUNT - 1

	? ALLTRIM(STR(resultado.item(n).index)) + " - " + ALLTRIM(STR(resultado.item(n).replacements, 10,2))

ENDFOR

**Comment by voxsoftware** [comment]
Please post the exception produced, or the error you are seeing.

**Comment by voxsoftware** [comment]
Ok, just now I checked, and there are many things that you need take care. 

1. In you c# code you are using ```resultado.Add(new outliers { index = datos[i,1], ``` but in c# arrays start in 0, so you need use ```resultado.Add(new outliers { index = datos[i,0], ...```

2. Just now there is no way to pass directly a VFP Array you need convert first to *kodnet* array. You can convert using a function like this: 

```xbase
FUNCTION convertArrayToKodnet(arr, dim1, dim2)
	LOCAL result 
	result = _screen.kodnet.getStaticWrapper("System.Double[,]").construct(m.dim1, m.dim2)

	FOR i = 1 TO m.dim1
		FOR y = 1 TO m.dim2 
			result.setValue(m.arr[m.i, m.y], m.i - 1, m.y - 1)
		ENDFOR 
	ENDFOR 
	RETURN m.result 
ENDFUNC 
```


3. After you convert to *kodnet* array, you can pass to c# function, but please don't use byref ```Routliers(ref double[,] datos)``` instead use ```Routliers(double[,] datos)``` 


I will put here a file with the corrections applied, fully tested and working

```xbase 
TEXT TO m.code noshow

using System;
using System.Collections.Generic;
using System.IO;

public class program{

public static void main(){


}
}

namespace Compiled
{

public class outliers{

    public double index { get; set; }

    public double replacements { get; set; }


}	


public class datos{

    public double consumo { get; set; }

}	


public class Test
{	
	
	
	public List<outliers> Routliers(double[,] datos) {

		List<outliers> resultado = new List<outliers>();

	        for (int i = 0; i < 19; i++)
	        {
		
	           resultado.Add(new outliers { index = datos[i,0], replacements = datos[i,0] });

		}	
	
	
		return resultado;
					
	}
	
	
	
	

	public static int ExecuteFunc(Func<string,int> func)
	{
		return func("Method executed from .NET");
	}
	
	public static int ExecuteFunc(Func<string,int> func, string message)
	{
		return func(message);
	}
	
	public static int ExecuteFunc(Func<string,int,string,int> func, string message, int option, string title)
	{
		return func(message,option,title);
	}
}
}

ENDTEXT

LOCAL engine

Local asem, test
engine = _screen.kodnet.getStaticWrapper("jxshell.csharplanguage").construct()
m.engine.Runscript(m.code)
asem = m.engine.getCompiledAssembly()
_Screen.kodnet.loadAssembly(m.asem)


test = _screen.kodnet.getStaticWrapper("Compiled.Test").construct()


LOCAL ARRAY m_datos(19, 1) as Double

m_datos(1,1) = 378
m_datos(2,1) = 327
m_datos(3,1) = 311
m_datos(4,1) = 329
m_datos(5,1) = 801
m_datos(6,1) = 1238
m_datos(7,1) = 449
m_datos(8,1) = 408
m_datos(9,1) = 452
m_datos(10,1) = 442
m_datos(11,1) = 947
m_datos(12,1) = 1617
m_datos(13,1) = 451
m_datos(14,1) = 495
m_datos(15,1) = 489
m_datos(16,1) = 391
m_datos(17,1) = 1182
m_datos(18,1) = 1132
m_datos(19,1) = 380




LOCAL kodnetArray 
m.kodnetArray = convertArrayTOKodnet(@m_datos, 19, 1)
resultado = test.Routliers(m.kodnetArray)

FOR n = 0 TO resultado.COUNT - 1

? ALLTRIM(STR(resultado.item(n).index)) + " - " + ALLTRIM(STR(resultado.item(n).replacements, 10,2))
ENDFOR



FUNCTION convertArrayToKodnet(arr, dim1, dim2)
	LOCAL result 
	result = _screen.kodnet.getStaticWrapper("System.Double[,]").construct(m.dim1, m.dim2)

	FOR i = 1 TO m.dim1
		FOR y = 1 TO m.dim2 
			result.setValue(m.arr[m.i, m.y], m.i - 1, m.y - 1)
		ENDFOR 
	ENDFOR 
	RETURN m.result 
ENDFUNC 
```
